#!/usr/bin/env python3
# Archive note (frozen 2026-09-25; as-run copy of
#   /mnt/shared/work/dh_response_bulk_labels_deltasub/delta_floor_analysis.py).
# Backs the label truncation floor quoted in the Track B manuscript (Methods
#   section "Metrics", and the Table 4 row "label truncation floor
#   (Richardson)"): the delta = 0.001 A label against the delta -> 0 limit.
# Richardson pairing used: (4 dH(0.0005 A) - dH(0.001 A))/3, the standard
#   (d/2, d) pair; the earlier 4:1-step pairing is still emitted as
#   relfro_d10_vs_richardson_legacypair and its report is kept as
#   delta_floor_report_legacy_20260913.json (non-destructive).
# V1_JOBS/DSUB/WORK/OUT below are the as-run absolute paths on the research
#   store; the deltasub jobs themselves are generated by gen_delta_inputs.py.
"""delta-Richardson label-floor analysis for the 4-component delta subset.

For each component: dense H at displaced geometries for delta in
{0.0005, 0.001, 0.002} A (0.001 from the original campaign scfouts, the
others from the deltasub jobs). Per-Bohr central differences, self-calibrated
from scfout positions. Reports cross-delta consistency and the Richardson
delta->0 limit: dH_R = (4 dH(d/2) - dH(d)) / 3 for O(d^2) central differences,
formed from the two SMALLER steps (0.0005, 0.001 A), with the largest step
(0.002 A) as a consistency check on the delta^2 scaling.

2026-09-25 correction: the original run built the extrapolation from the pair
(0.0005, 0.002 A) -- a 4:1 step ratio -- with the 2:1 coefficient, which does
not cancel the delta^2 term and overstates the floor by ~1.14x (median
0.1365% vs 0.1200%). Both values are reported; the pair-based one is the
floor quoted in the manuscript.

Floor question: how much of the model's 0.064 relfro (vs labels) is label
truncation/cancellation error rather than model error?
"""
import json
import sys
from pathlib import Path

import numpy as np

REPO = Path("/home/duguex/defect_research/repos/slurm-4090-guide/.worktrees/dh-response-paper")
sys.path.insert(0, str(REPO))

from scripts.diff_hamgnn.bulk_band_response_eval import _extract_hs, _dense_hs  # noqa: E402

READER = Path("/tmp/read_openmx_standalone")
V1_JOBS = Path("/mnt/shared/work/dh_response_bulk_labels_v1/jobs")
DSUB = Path("/mnt/shared/work/dh_response_bulk_labels_deltasub")
WORK = DSUB / "extract"
OUT = DSUB / "delta_floor_report.json"

COMPONENTS = [
    ("Bulk04_chg0_atom060_axis1", 60, 1),
    ("Bulk04_chg0_atom028_axis0", 28, 0),
    ("Bulk19_chg0_atom007_axis2", 7, 2),
    ("Bulk19_chg0_atom032_axis1", 32, 1),
]


def scfout_pair(comp: str, delta: float) -> tuple[Path, Path]:
    if delta == 0.001:
        base = V1_JOBS / comp
        return base / "plus" / f"{comp}_plus.scfout", base / "minus" / f"{comp}_minus.scfout"
    tag = "d0005" if delta == 0.0005 else "d002"
    stub_p, stub_m = f"{comp}_{tag}p", f"{comp}_{tag}m"
    return (
        DSUB / "jobs" / comp / stub_p / f"{stub_p}.scfout",
        DSUB / "jobs" / comp / stub_m / f"{stub_m}.scfout",
    )


def dense_dh(pair: tuple[Path, Path], atom: int, axis: int) -> tuple[np.ndarray, float]:
    # cache key must be unique per component: v1 pairs both live in dirs called
    # plus/minus, so key on the component dir + direction
    key_p = f"{pair[0].parent.parent.name}_{pair[0].parent.name}"
    key_m = f"{pair[1].parent.parent.name}_{pair[1].parent.name}"
    hp = _extract_hs(READER, pair[0], WORK / key_p)
    hm = _extract_hs(READER, pair[1], WORK / key_m)
    Hp, _ = _dense_hs(hp)
    Hm, _ = _dense_hs(hm)
    dc = float(hp["pos"][atom, axis] - hm["pos"][atom, axis]) / 2.0
    if not (1e-6 < abs(dc) < 1e-1):
        raise RuntimeError(f"{pair[0]}: implausible displacement {dc}")
    return (Hp - Hm) / (2.0 * dc), dc


def main() -> None:
    report: dict = {"components": {}}
    for comp, atom, axis in COMPONENTS:
        dh, dcs = {}, {}
        for delta in (0.0005, 0.001, 0.002):
            dh[delta], dcs[delta] = dense_dh(scfout_pair(comp, delta), atom, axis)
        d05, d10, d20 = dh[0.0005], dh[0.001], dh[0.002]
        # Richardson delta->0 for O(d^2) central differences, (delta/2, delta) pair
        rich = (4.0 * d05 - d10) / 3.0
        # original 2026-09-13 formula: 4:1 pair (0.0005, 0.002) with the 2:1
        # coefficient -- kept for traceability, do not use as the floor
        rich_legacy = (4.0 * d05 - d20) / 3.0

        def relfro(a, b):
            return float(np.linalg.norm(a - b) / np.linalg.norm(b))

        res = {
            "delta_c_bohr": {str(k): v for k, v in dcs.items()},
            "norm_dH": {str(k): float(np.linalg.norm(v)) for k, v in dh.items()},
            "relfro_d05_vs_d10": relfro(d05, d10),
            "relfro_d20_vs_d10": relfro(d20, d10),
            "relfro_d10_vs_richardson": relfro(d10, rich),
            "relfro_d10_vs_richardson_legacypair": relfro(d10, rich_legacy),
        }
        report["components"][comp] = res
        print(comp, json.dumps(res), flush=True)

    def med(key):
        return float(np.median([report["components"][c][key] for c in report["components"]]))

    report["summary_median"] = {
        "relfro_d05_vs_d10": med("relfro_d05_vs_d10"),
        "relfro_d20_vs_d10": med("relfro_d20_vs_d10"),
        "relfro_d10_vs_richardson": med("relfro_d10_vs_richardson"),
        "relfro_d10_vs_richardson_legacypair": med("relfro_d10_vs_richardson_legacypair"),
        "note": "per-Bohr derivatives; relfro_d10_vs_richardson (pair 0.0005/0.001) = truncation error of the delta=0.001 label convention; _legacypair = the 2026-09-13 mismatched-pair value",
    }
    print("SUMMARY", json.dumps(report["summary_median"], indent=1))
    OUT.write_text(json.dumps(report, indent=1))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
